#!/bin/bash
# Alternative chat-title selector without Python.
# Because Python is awful.

if [ "$(date "+%m%d")" == "1016" ]; then
	printf "Krak's Birthday Today"
	exit 0
fi

titles=(
	"Krakchat (Maybe a Beta, but Alpha as Fuck)"
	"Krakchat (Somehow still beta!)"
	"Krakchat (Bring it all back to you!)"
	"Krakchat (For science!)"
	"Krakchat (AJAX'd up and good to go!)"
	"Krakchat (Websockets maybe!)"
	"Krakchat (Something something liquor store)"
	"Krakchat (Go home. You are drunk.)"
	"Krakchat (Fucking Chris.)"
	"Krakchat (Missed my own birthday party.)"
	"Krakchat (Dad, you promised.)"
	"Krakchat (Fuck you, pay me!)"
	"Krakchat (You're going to like, whether you like it or not.)"
	"Krakchat (Wearing my tail.)"
	"Krakchat (ssh -R)"
	"Krakchat (Alexander feels a strange pulling sensation.)"
	"Krakchat (Possibly NSFW.)"
	"Krakchat (Somebody owes me a blowjob.)"
	"Krakchat (Been waitin' a long time for this!)"
	"Krakchat (Maybe Eventually.)"
	"Krakchat (When it's Done.)"
	"Krakchat (Still in Closed Beta.)"
	"Krakcat (meow)"
	"Krakchat (Mammaries.)"
	"Krakchat (Selling Your Soul to the Russians.)"
	"Krakchat (AJAX is Awful.)"
	"Krakchat (Fell in a Parking Lot.)"
	"Krakchat (It's 30 Dollars Cheaper.)"
	"Krakchat (Shaw's sucks.)"
	"Krakchat (Check out my Papes!)"
	"Krakchat (Definitely not a Linux circlejerk.)"
	"Krakchat (Still no iOS App.)"
	"Krakchat (Asian on Friday?)"
	"Krakchat (Taylor Swift)"
	"Krakchat (Preferences Coming Soon.)"
	"Krakchat (200 ping? Must be Brazilian)"
	"Krakchat (AWPing Mid Doors)"
	"Krakchat (Don't Buy the Bizon)"
	"Krakchat (Back at the Ranch)"
	"Krakchat (Let's Take a Break)"
	"Krakchat (<marquee><blink>"
	"Krakchat (Don't go to City Music)"
	"Krakchat (Definitely has ants)"
	"Krakchat (No Bugs, Just Ants)"
	"Krakchat (But, Does it Have Ants?)"
	"Krakchat (CLAM BATTLE)"
	"Krakchat (Try the Ancient Link!)"
	"Krakchat (Ported to krakws!)"
	"Krakchat (It's a raid night!)"
	"Krakchat (Drunk at Anthrocon)"
	"Krakchat (I fucking hate Windows)"
	"Krakchat (Congratu-pony-lations, fillies!)"
	"Krakchat (Definitely Arabic)"
	"Krakchat (That's hot.)"
	"Krakchat (BBPLS is my New Backend)"
	"Krakchat (Because I haven't finished Krakden)"
	"Krakchat (Russell, honey ...)"
	"Krakchat (I mean, ...)"
	"Krakchat (On the rocks next time)"
	"Krakchat (There was a loud report)"
	"Krakchat (Less fun than Anthrocon)"
	"Krakchat (Where did you think I learned to get shitty?)"
	"Krakchat (Smashing martini glasses)"
	"Krakchat (Lemonbrat hoodies for everyone!)"
	"Krakchat (Don't Go Jason Waterfalls)"
)
pick=$RANDOM
let "pick %= ${#titles[@]}"
printf "%s" "${titles[$pick]}"
